In [1]:
print 123

SyntaxError: Missing parentheses in call to 'print'. Did you mean print(123)? (<ipython-input-1-fb941b049711>, line 1)

In [2]:
print(123)

123


In [3]:
import numy as np

ModuleNotFoundError: No module named 'numy'

In [4]:
import numpy as np

In [10]:
arr =np.array([[1,2,3],[4,5,6]])
type(arr)

numpy.ndarray

In [12]:
arr.shape

(2, 3)

In [13]:
arr.size

6

In [14]:
arr.dtype

dtype('int32')

In [15]:
arr2=np.zeros((3,4))
print(arr2)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [20]:
arr3=np.ones((1,5))
print(arr3)

[[1. 1. 1. 1. 1.]]


In [21]:
arr4=np.eye(5)
print(arr4)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [26]:
np.arange(0,30)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [31]:
np.linspace(0,2,100000)

array([0.00000e+00, 2.00002e-05, 4.00004e-05, ..., 1.99996e+00,
       1.99998e+00, 2.00000e+00])

In [35]:
arr.reshape(2,2,4)

ValueError: cannot reshape array of size 6 into shape (2,2,4)

In [37]:
arr[1:,1:]

array([[5, 6]])

In [38]:
arr+1

array([[2, 3, 4],
       [5, 6, 7]])

In [39]:
arr.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [40]:
arr.max(axis=1)

array([3, 6])

In [41]:
arr.max()

6

In [42]:
arr.max(axis=0)

array([4, 5, 6])

In [44]:
np.sort(arr)

array([[1, 2, 3],
       [4, 5, 6]])

In [47]:
np.hsplit?

In [48]:
x = np.arange(16.0).reshape(4, 4)

In [49]:
print(x)

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]]


In [51]:
np.hsplit(x,2)

[array([[ 0.,  1.],
        [ 4.,  5.],
        [ 8.,  9.],
        [12., 13.]]),
 array([[ 2.,  3.],
        [ 6.,  7.],
        [10., 11.],
        [14., 15.]])]